# Generated by Django 2.1 on 2018-09-20 18:05

from django.db import migrations, models
import mlm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatherName', models.CharField(max_length=250)),
                ('motherName', models.CharField(max_length=250)),
                ('userId', models.ForeignKey(on_delete=mlm.models.UserTable, related_name='parentTable', to='mlm.ParentTable')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('userName', models.CharField(max_length=250)),
            ],
        ),
    ]
