# Generated by Django 2.1 on 2018-09-20 18:05

from django.db import migrations, models
import mlm.models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiblingsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brother', models.CharField(max_length=250)),
                ('sister', models.CharField(max_length=250)),
                ('userId', models.ForeignKey(on_delete=mlm.models.UserTable, related_name='siblingsTable', to='mlm.SiblingsTable')),
            ],
        ),
    ]
