# Generated by Django 2.1 on 2018-09-21 18:14

from django.db import migrations, models
import mlm.models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0002_siblingstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='childrenTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son', models.CharField(max_length=250)),
                ('sonPhone', models.CharField(blank=True, max_length=15, unique=True)),
                ('daughter', models.CharField(max_length=250)),
                ('daughterPhone', models.CharField(blank=True, max_length=15, unique=True)),
                ('userId', models.ForeignKey(on_delete=mlm.models.UserTable, related_name='childrenTable', to='mlm.childrenTable')),
            ],
        ),
        migrations.CreateModel(
            name='wifeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wife', models.CharField(max_length=250)),
                ('wifePhone', models.CharField(blank=True, max_length=15, unique=True)),
                ('userId', models.ForeignKey(on_delete=mlm.models.UserTable, related_name='wifeTable', to='mlm.wifeTable')),
            ],
        ),
        migrations.AddField(
            model_name='parenttable',
            name='fatherPhone',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='parenttable',
            name='motherPhone',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='siblingstable',
            name='brotherPhone',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='siblingstable',
            name='sisterPhone',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
