# Generated by Django 2.1 on 2018-09-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=264)),
                ('lastName', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
    ]
