# Generated by Django 2.1 on 2018-09-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formalName', models.CharField(max_length=250)),
                ('nickName', models.CharField(max_length=250)),
                ('fathername', models.CharField(max_length=250)),
                ('motherName', models.CharField(max_length=250)),
                ('contactNumber', models.CharField(max_length=20, unique=True)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('religion', models.CharField(choices=[('ISM', 'Islam'), ('HIN', 'Hindu'), ('OTH', 'Others')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
