# Generated by Django 2.1 on 2018-09-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnmodelform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fathername',
        ),
        migrations.RemoveField(
            model_name='user',
            name='motherName',
        ),
    ]
